Write-Host ""
Write-Host "Pirate Ocean Portfolio root commands"
Write-Host ""
Write-Host "npm run start-application  Start frontend and backend in separate terminals"
Write-Host "npm run dev                Alias for start-application"
Write-Host "npm run dev:frontend       Start only the frontend"
Write-Host "npm run dev:backend        Start only the backend"
Write-Host "npm run install:all        Install frontend and backend dependencies"
Write-Host "npm run check              Run backend typecheck and frontend lint"
Write-Host "npm run build              Build backend and frontend"
Write-Host "npm run lint:frontend      Lint only the frontend"
Write-Host "npm run typecheck:backend  Typecheck only the backend"
Write-Host "npm run demo:api           Call demo backend endpoints"
Write-Host ""
